package art.gallery;

import static art.gallery.form0.s;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class form17 extends javax.swing.JFrame {
ArtGallery artgallery;
 Artwork art ;
  form17 f ;
  form1 f1;
static     String artTitle=null;
static   String art_path=null;
 
    public form17(String path,String name){
    
    artTitle=name;
    art_path=path;
    }
   public form17() throws IOException {
        initComponents();
          this.setLocationRelativeTo(null);
         
         File file = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Melting Watch.jpg");
         jLabel8.setIcon(new ImageIcon(artgallery.loading.read_images(file)));
         File file2 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Mona Lisa.jpg");
         jLabel7.setIcon(new ImageIcon(artgallery.loading.read_images(file2)));
         File file3 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Cafe Terrace,Place du Forum,Arles.jpg");
         jLabel9.setIcon(new ImageIcon(artgallery.loading.read_images(file3)));
         File file4 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.the-endless-enigma.jpg");
         jLabel10.setIcon(new ImageIcon(artgallery.loading.read_images(file4)));
         File file5 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Persistence of Memory.jpg");
         jLabel13.setIcon(new ImageIcon(artgallery.loading.read_images(file5)));
         File file6 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Madonna of the Yarnwinder.jpg");
         jLabel14.setIcon(new ImageIcon(artgallery.loading.read_images(file6)));
         File file7 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Still Life - Vase with Fifteen Sunflowers.jpg");
         jLabel15.setIcon(new ImageIcon(artgallery.loading.read_images(file7)));
         File file8 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.The Last Supper.jpg");
         jLabel17.setIcon(new ImageIcon(artgallery.loading.read_images(file8)));
        if (art_path!=null){
         File f10 = new File(art_path);
         jLabel49.setIcon(new ImageIcon(artgallery.loading.read_images(f10)));
                  }
         File file9 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\forms (2).jpg");
         jLabel1.setIcon(new ImageIcon(artgallery.loading.read_images(file9)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hoverbar = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 570));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(123, 80, 38));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(247, 247, 199));
        jButton5.setText("Return Back");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(247, 247, 199), new java.awt.Color(247, 247, 199)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(744, 423, 130, 50);

        jLabel7.setBackground(new java.awt.Color(255, 153, 204));
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel7.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 65, 110, 150);

        jLabel8.setBackground(new java.awt.Color(255, 153, 204));
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(144, 63, 110, 150);

        jLabel9.setBackground(new java.awt.Color(255, 153, 204));
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel9.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(284, 63, 110, 150);

        jLabel10.setBackground(new java.awt.Color(255, 153, 204));
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel10.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(424, 63, 110, 150);

        jLabel13.setBackground(new java.awt.Color(255, 153, 204));
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel13.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(14, 303, 110, 150);

        jLabel14.setBackground(new java.awt.Color(255, 153, 204));
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel14.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel14.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(144, 303, 110, 150);

        jLabel15.setBackground(new java.awt.Color(255, 153, 204));
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel15.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel15.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel15.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(284, 303, 110, 150);

        jLabel17.setBackground(new java.awt.Color(255, 153, 204));
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel17.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel17.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel17.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(424, 303, 110, 150);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/left-arrow.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(704, 423, 40, 50);

        jLabel4.setBackground(new java.awt.Color(247, 247, 199));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(123, 80, 38));
        jLabel4.setText("Paintings");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(123, 80, 38), new java.awt.Color(123, 80, 38)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 10, 190, 40);

        jTextField27.setEditable(false);
        jTextField27.setBackground(new java.awt.Color(225, 225, 161));
        jTextField27.setForeground(new java.awt.Color(123, 80, 38));
        jTextField27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField27);
        jTextField27.setBounds(184, 263, 30, 20);

        jTextField28.setEditable(false);
        jTextField28.setBackground(new java.awt.Color(225, 225, 161));
        jTextField28.setForeground(new java.awt.Color(123, 80, 38));
        jTextField28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField28);
        jTextField28.setBounds(224, 263, 30, 20);

        jTextField29.setEditable(false);
        jTextField29.setBackground(new java.awt.Color(225, 225, 161));
        jTextField29.setForeground(new java.awt.Color(123, 80, 38));
        jTextField29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField29);
        jTextField29.setBounds(324, 263, 30, 20);

        jTextField30.setEditable(false);
        jTextField30.setBackground(new java.awt.Color(225, 225, 161));
        jTextField30.setForeground(new java.awt.Color(123, 80, 38));
        jTextField30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField30);
        jTextField30.setBounds(364, 263, 30, 20);

        jTextField31.setEditable(false);
        jTextField31.setBackground(new java.awt.Color(225, 225, 161));
        jTextField31.setForeground(new java.awt.Color(123, 80, 38));
        jTextField31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField31);
        jTextField31.setBounds(464, 263, 30, 20);

        jTextField32.setEditable(false);
        jTextField32.setBackground(new java.awt.Color(225, 225, 161));
        jTextField32.setForeground(new java.awt.Color(123, 80, 38));
        jTextField32.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField32);
        jTextField32.setBounds(504, 263, 30, 20);

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(225, 225, 161));
        jTextField26.setForeground(new java.awt.Color(123, 80, 38));
        jTextField26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField26);
        jTextField26.setBounds(94, 263, 30, 20);

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(225, 225, 161));
        jTextField25.setForeground(new java.awt.Color(123, 80, 38));
        jTextField25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField25);
        jTextField25.setBounds(54, 263, 30, 20);

        jTextField33.setEditable(false);
        jTextField33.setBackground(new java.awt.Color(225, 225, 161));
        jTextField33.setForeground(new java.awt.Color(123, 80, 38));
        jTextField33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField33);
        jTextField33.setBounds(184, 503, 30, 20);

        jTextField34.setEditable(false);
        jTextField34.setBackground(new java.awt.Color(225, 225, 161));
        jTextField34.setForeground(new java.awt.Color(123, 80, 38));
        jTextField34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField34);
        jTextField34.setBounds(224, 503, 30, 20);

        jTextField35.setEditable(false);
        jTextField35.setBackground(new java.awt.Color(225, 225, 161));
        jTextField35.setForeground(new java.awt.Color(123, 80, 38));
        jTextField35.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField35);
        jTextField35.setBounds(324, 503, 30, 20);

        jTextField36.setEditable(false);
        jTextField36.setBackground(new java.awt.Color(225, 225, 161));
        jTextField36.setForeground(new java.awt.Color(123, 80, 38));
        jTextField36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField36);
        jTextField36.setBounds(364, 503, 30, 20);

        jTextField37.setEditable(false);
        jTextField37.setBackground(new java.awt.Color(225, 225, 161));
        jTextField37.setForeground(new java.awt.Color(123, 80, 38));
        jTextField37.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField37);
        jTextField37.setBounds(464, 503, 30, 20);

        jTextField38.setEditable(false);
        jTextField38.setBackground(new java.awt.Color(225, 225, 161));
        jTextField38.setForeground(new java.awt.Color(123, 80, 38));
        jTextField38.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField38);
        jTextField38.setBounds(504, 503, 30, 20);

        jTextField39.setEditable(false);
        jTextField39.setBackground(new java.awt.Color(225, 225, 161));
        jTextField39.setForeground(new java.awt.Color(123, 80, 38));
        jTextField39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField39);
        jTextField39.setBounds(94, 503, 30, 20);

        jTextField40.setEditable(false);
        jTextField40.setBackground(new java.awt.Color(225, 225, 161));
        jTextField40.setForeground(new java.awt.Color(123, 80, 38));
        jTextField40.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField40);
        jTextField40.setBounds(54, 503, 30, 20);

        jButton6.setBackground(new java.awt.Color(123, 80, 38));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/volume-off-indicator 32.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 10, 40, 40);

        jButton7.setBackground(new java.awt.Color(123, 80, 38));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/audio-speaker-on.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(60, 10, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 220, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 220, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 220, 40, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 220, 40, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18);
        jLabel18.setBounds(220, 220, 40, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(280, 220, 40, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20);
        jLabel20.setBounds(320, 220, 40, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(360, 220, 40, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(420, 220, 40, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(460, 220, 40, 40);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24);
        jLabel24.setBounds(500, 220, 40, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25);
        jLabel25.setBounds(10, 460, 40, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26);
        jLabel26.setBounds(50, 460, 40, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27);
        jLabel27.setBounds(90, 460, 40, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel28);
        jLabel28.setBounds(220, 460, 40, 40);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel29);
        jLabel29.setBounds(180, 460, 40, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel30);
        jLabel30.setBounds(140, 460, 40, 40);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel31);
        jLabel31.setBounds(360, 460, 40, 40);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel32);
        jLabel32.setBounds(320, 460, 40, 40);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel33);
        jLabel33.setBounds(280, 460, 40, 40);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel34);
        jLabel34.setBounds(420, 460, 40, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel35);
        jLabel35.setBounds(460, 460, 40, 40);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel36);
        jLabel36.setBounds(500, 460, 40, 40);

        Hoverbar.setEditable(false);
        Hoverbar.setBackground(new java.awt.Color(123, 80, 38));
        Hoverbar.setColumns(20);
        Hoverbar.setForeground(new java.awt.Color(247, 247, 199));
        Hoverbar.setRows(5);
        Hoverbar.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        Hoverbar.setPreferredSize(new java.awt.Dimension(270, 260));
        jScrollPane1.setViewportView(Hoverbar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 20, 330, 200);

        jLabel49.setBackground(new java.awt.Color(255, 153, 204));
        jLabel49.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel49.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel49.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel49.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel49);
        jLabel49.setBounds(560, 300, 110, 150);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel50);
        jLabel50.setBounds(640, 460, 40, 40);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel40);
        jLabel40.setBounds(560, 460, 40, 40);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel51);
        jLabel51.setBounds(600, 460, 40, 40);

        jTextField43.setEditable(false);
        jTextField43.setBackground(new java.awt.Color(225, 225, 161));
        jTextField43.setForeground(new java.awt.Color(123, 80, 38));
        jTextField43.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField43);
        jTextField43.setBounds(600, 500, 30, 20);

        jTextField44.setEditable(false);
        jTextField44.setBackground(new java.awt.Color(225, 225, 161));
        jTextField44.setForeground(new java.awt.Color(123, 80, 38));
        jTextField44.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField44);
        jTextField44.setBounds(640, 500, 30, 20);
        getContentPane().add(jLabel37);
        jLabel37.setBounds(590, 400, 40, 40);

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        form7 f7 = null;
        f7 = new form7();
        f7.setVisible(true);
     
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          s.Pflag=false;
        s.pause();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
             s.Cflag=false;
        s.play();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Mona Lisa");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField25.setText(String.valueOf(art.getLike()));
  jTextField26.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Melting Watch");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField27.setText(String.valueOf(art.getLike()));
  jTextField28.setText(String.valueOf(art.getDislike()));
  
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Cafe Terrace,Place du Forum,Arles");
 Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField29.setText(String.valueOf(art.getLike()));
  jTextField30.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("the-endless-enigma");
 Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField31.setText(String.valueOf(art.getLike()));
  jTextField32.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Persistence of Memory");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField40.setText(String.valueOf(art.getLike()));
  jTextField39.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Madonna of the Yarnwinder");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField33.setText(String.valueOf(art.getLike()));
  jTextField34.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Still Life - Vase with Fifteen Sunflowers");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField35.setText(String.valueOf(art.getLike()));
  jTextField36.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("The Last Supper");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField37.setText(String.valueOf(art.getLike()));
  jTextField38.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
      
        art=artgallery.loading.ArtWork.get("Mona Lisa");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
        
           JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Mona Lisa", art);
          
            try { 
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
          
         }
           
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Mona Lisa");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Mona Lisa", art);
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("Mona Lisa");
         int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
          artgallery.loading.ArtWork.put("Mona Lisa", art);
         
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Melting Watch");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
        JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Melting Watch", art);
            try {
               
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
                
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Melting Watch");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Melting Watch", art);
         try {
         artgallery.loading.add_Artwork(artgallery.loading);
     } catch (IOException ex) {
         Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Melting Watch");
         int dislike=art.getDislike();
         dislike+=1;
        art.setDislike(dislike);
          artgallery.loading.ArtWork.put("Melting Watch", art);
          try {
         artgallery.loading.add_Artwork(artgallery.loading);
     } catch (IOException ex) {
         Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
              art=artgallery.loading.ArtWork.get("Cafe Terrace,Place du Forum,Arles");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
        JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Cafe Terrace,Place du Forum,Arles", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("Cafe Terrace,Place du Forum,Arles");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Cafe Terrace,Place du Forum,Arles", art);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Cafe Terrace,Place du Forum,Arles");
         int dislike=art.getDislike();
         dislike+=1;
       art.setDislike(dislike);
          artgallery.loading.ArtWork.put("Cafe Terrace,Place du Forum,Arles", art);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("the-endless-enigma");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
         JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("the-endless-enigma", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("the-endless-enigma");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("the-endless-enigma", art);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("the-endless-enigma");
         int dislike=art.getDislike();
         dislike+=1;
        art.setDislike(dislike);
          artgallery.loading.ArtWork.put("the-endless-enigma", art);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Persistence of Memory");
       
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
        JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Persistence of Memory", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("Persistence of Memory");
        int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Persistence of Memory", art);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Persistence of Memory");
          int dislike=art.getDislike();
         dislike+=1;
        art.setDislike(dislike);
        artgallery.loading.ArtWork.put("Persistence of Memory", art);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Madonna of the Yarnwinder");
       
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
        JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Madonna of the Yarnwinder", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Madonna of the Yarnwinder");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Madonna of the Yarnwinder", art);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Madonna of the Yarnwinder");
         int dislike=art.getDislike();
         dislike+=1;
        art.setDislike(dislike);
        artgallery.loading.ArtWork.put("Madonna of the Yarnwinder", art);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Still Life - Vase with Fifteen Sunflowers");
       
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
        JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Still Life - Vase with Fifteen Sunflowers", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("Still Life - Vase with Fifteen Sunflowers");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Still Life - Vase with Fifteen Sunflowers", art);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Still Life - Vase with Fifteen Sunflowers");
         int dislike=art.getDislike();
         dislike+=1;
        art.setDislike(dislike);
        artgallery.loading.ArtWork.put("Still Life - Vase with Fifteen Sunflowers", art);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        
                    art=artgallery.loading.ArtWork.get("The Last Supper");
       
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(f,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
        JOptionPane.showMessageDialog(f,"Done ","Shopping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("The Last Supper", art);
                        try {
                            f1.cust.Buy_anyitem(art.getPrice(), form1.cust);
                        } catch (IOException ex) {
                            Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
                        }
        }
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("The Last Supper");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("The Last Supper", art);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("The Last Supper");
         int dislike=art.getDislike();
        art.setDislike(dislike++);
        artgallery.loading.ArtWork.put("The Last Supper", art);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        // TODO add your handling code here:
                art=artgallery.loading.ArtWork.get(artTitle);
                     Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                            art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                            "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                            "Artist Birthplace: "+art.getA().Birthplace+"\n"
                            +"Artist Age: "+art.getA().Age+"\n"+
                            "Category: "+art.getA().Category);
          jTextField43.setText(String.valueOf(art.getLike()));
          jTextField44.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
                  art=artgallery.loading.ArtWork.get(artTitle);
                 int dislike=art.getDislike();
                  dislike+=1;
                 art.setDislike(dislike);
                  artgallery.loading.ArtWork.put(artTitle, art);
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
             art=artgallery.loading.ArtWork.get(artTitle);
                if (art.getCount()==0)
                    JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
                else {
                      JOptionPane.showMessageDialog(null,"Done ","Shopping process",JOptionPane.INFORMATION_MESSAGE);
                      int count =art.getCount();
                              count-=1;
                              art.setCount(count);
                      artgallery.loading.ArtWork.put(artTitle, art);
                        try {
                                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
                            } catch (IOException ex) {
                                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
                            }
            
                     }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
                 art=artgallery.loading.ArtWork.get(artTitle);
                 int like=art.getLike();
                 like+=1;
                 art.setLike(like);
                 artgallery.loading.ArtWork.put(artTitle, art);
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
Hoverbar.setText(" ");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         try {
        artgallery.loading.add_Artwork(artgallery.loading);
        artgallery.loading.write_Customer(artgallery.loading);
    } catch (IOException ex) {
        Logger.getLogger(form10.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form17().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Hoverbar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    // End of variables declaration//GEN-END:variables
}
