/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art.gallery;

import static art.gallery.form0.s;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class form16 extends javax.swing.JFrame {

ArtGallery artgallery;
 Artwork art ;
  form1 f1;
  form16 f;
  static  String artTitle=null;
  static String art_path=null;
 
    public form16(String path,String name){
    
    artTitle=name;
    art_path=path;
    }
    public form16() throws IOException {
        initComponents();
          this.setLocationRelativeTo(null);
         
initComponents();
         File file = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Anachorète endormi.jpg");
         jLabel8.setIcon(new ImageIcon(artgallery.loading.read_images(file)));
         File file2 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Blue Marquise.jpg");
         jLabel7.setIcon(new ImageIcon(artgallery.loading.read_images(file2)));
         File file3 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.the death ofo edipus.jpg");
         jLabel9.setIcon(new ImageIcon(artgallery.loading.read_images(file3)));
         File file4 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.the nightmare.jpg");
         jLabel10.setIcon(new ImageIcon(artgallery.loading.read_images(file4)));
         File file5 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.The Seller of Cupids.jpg");
         jLabel13.setIcon(new ImageIcon(artgallery.loading.read_images(file5)));
         File file6 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Union_of_Lublin.jpg");
         jLabel14.setIcon(new ImageIcon(artgallery.loading.read_images(file6)));
         File file7 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\.Sweet Melancholy.jpg");
         jLabel15.setIcon(new ImageIcon(artgallery.loading.read_images(file7)));
         if (art_path!=null){
         File file8 = new File(art_path);
         jLabel52.setIcon(new ImageIcon(art_path));
         
         }
         File file9 = new File("E:\\Final l Final\\Final\\build\\classes\\art\\art\\forms (2).jpg");
         jLabel1.setIcon(new ImageIcon(artgallery.loading.read_images(file9)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hoverbar = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 570));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(123, 80, 38));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(247, 247, 199));
        jButton5.setText("Return Back");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(247, 247, 199), new java.awt.Color(247, 247, 199)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 420, 130, 50);

        jLabel7.setBackground(new java.awt.Color(255, 153, 204));
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel7.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 65, 110, 150);

        jLabel8.setBackground(new java.awt.Color(255, 153, 204));
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(144, 63, 110, 150);

        jLabel9.setBackground(new java.awt.Color(255, 153, 204));
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel9.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(284, 63, 110, 150);

        jLabel10.setBackground(new java.awt.Color(255, 153, 204));
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel10.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(424, 63, 110, 150);

        jLabel13.setBackground(new java.awt.Color(255, 153, 204));
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel13.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(14, 303, 110, 150);

        jLabel14.setBackground(new java.awt.Color(255, 153, 204));
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel14.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel14.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(144, 303, 110, 150);

        jLabel15.setBackground(new java.awt.Color(255, 153, 204));
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel15.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel15.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel15.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(284, 303, 110, 150);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/left-arrow.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(680, 420, 40, 50);

        jTextField27.setEditable(false);
        jTextField27.setBackground(new java.awt.Color(225, 225, 161));
        jTextField27.setForeground(new java.awt.Color(123, 80, 38));
        jTextField27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField27);
        jTextField27.setBounds(184, 263, 30, 20);

        jTextField28.setEditable(false);
        jTextField28.setBackground(new java.awt.Color(225, 225, 161));
        jTextField28.setForeground(new java.awt.Color(123, 80, 38));
        jTextField28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField28);
        jTextField28.setBounds(224, 263, 30, 20);

        jTextField29.setEditable(false);
        jTextField29.setBackground(new java.awt.Color(225, 225, 161));
        jTextField29.setForeground(new java.awt.Color(123, 80, 38));
        jTextField29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField29);
        jTextField29.setBounds(324, 263, 30, 20);

        jTextField30.setEditable(false);
        jTextField30.setBackground(new java.awt.Color(225, 225, 161));
        jTextField30.setForeground(new java.awt.Color(123, 80, 38));
        jTextField30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField30);
        jTextField30.setBounds(364, 263, 30, 20);

        jTextField31.setEditable(false);
        jTextField31.setBackground(new java.awt.Color(225, 225, 161));
        jTextField31.setForeground(new java.awt.Color(123, 80, 38));
        jTextField31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField31);
        jTextField31.setBounds(464, 263, 30, 20);

        jTextField32.setEditable(false);
        jTextField32.setBackground(new java.awt.Color(225, 225, 161));
        jTextField32.setForeground(new java.awt.Color(123, 80, 38));
        jTextField32.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField32);
        jTextField32.setBounds(504, 263, 30, 20);

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(225, 225, 161));
        jTextField26.setForeground(new java.awt.Color(123, 80, 38));
        jTextField26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField26);
        jTextField26.setBounds(94, 263, 30, 20);

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(225, 225, 161));
        jTextField25.setForeground(new java.awt.Color(123, 80, 38));
        jTextField25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField25);
        jTextField25.setBounds(54, 263, 30, 20);

        jTextField33.setEditable(false);
        jTextField33.setBackground(new java.awt.Color(225, 225, 161));
        jTextField33.setForeground(new java.awt.Color(123, 80, 38));
        jTextField33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField33);
        jTextField33.setBounds(184, 503, 30, 20);

        jTextField34.setEditable(false);
        jTextField34.setBackground(new java.awt.Color(225, 225, 161));
        jTextField34.setForeground(new java.awt.Color(123, 80, 38));
        jTextField34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField34);
        jTextField34.setBounds(224, 503, 30, 20);

        jTextField35.setEditable(false);
        jTextField35.setBackground(new java.awt.Color(225, 225, 161));
        jTextField35.setForeground(new java.awt.Color(123, 80, 38));
        jTextField35.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField35);
        jTextField35.setBounds(324, 503, 30, 20);

        jTextField36.setEditable(false);
        jTextField36.setBackground(new java.awt.Color(225, 225, 161));
        jTextField36.setForeground(new java.awt.Color(123, 80, 38));
        jTextField36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField36);
        jTextField36.setBounds(364, 503, 30, 20);

        jTextField39.setEditable(false);
        jTextField39.setBackground(new java.awt.Color(225, 225, 161));
        jTextField39.setForeground(new java.awt.Color(123, 80, 38));
        jTextField39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField39);
        jTextField39.setBounds(94, 503, 30, 20);

        jTextField40.setEditable(false);
        jTextField40.setBackground(new java.awt.Color(225, 225, 161));
        jTextField40.setForeground(new java.awt.Color(123, 80, 38));
        jTextField40.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField40);
        jTextField40.setBounds(54, 503, 30, 20);

        jButton6.setBackground(new java.awt.Color(123, 80, 38));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/volume-off-indicator 32.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 10, 40, 40);

        jButton7.setBackground(new java.awt.Color(123, 80, 38));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/audio-speaker-on.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(60, 10, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 220, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 220, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 220, 40, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 220, 40, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18);
        jLabel18.setBounds(220, 220, 40, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(280, 220, 40, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20);
        jLabel20.setBounds(320, 220, 40, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(360, 220, 40, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(420, 220, 40, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(460, 220, 40, 40);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24);
        jLabel24.setBounds(500, 220, 40, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25);
        jLabel25.setBounds(10, 460, 40, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26);
        jLabel26.setBounds(50, 460, 40, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27);
        jLabel27.setBounds(90, 460, 40, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel28);
        jLabel28.setBounds(220, 460, 40, 40);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel29);
        jLabel29.setBounds(180, 460, 40, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel30);
        jLabel30.setBounds(140, 460, 40, 40);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel31);
        jLabel31.setBounds(360, 460, 40, 40);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel32);
        jLabel32.setBounds(320, 460, 40, 40);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel33);
        jLabel33.setBounds(280, 460, 40, 40);

        jLabel4.setBackground(new java.awt.Color(247, 247, 199));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(123, 80, 38));
        jLabel4.setText("19th Century");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(123, 80, 38), new java.awt.Color(123, 80, 38)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 10, 250, 40);

        Hoverbar.setEditable(false);
        Hoverbar.setBackground(new java.awt.Color(123, 80, 38));
        Hoverbar.setColumns(20);
        Hoverbar.setForeground(new java.awt.Color(247, 247, 199));
        Hoverbar.setRows(5);
        Hoverbar.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        Hoverbar.setPreferredSize(new java.awt.Dimension(270, 260));
        jScrollPane1.setViewportView(Hoverbar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 30, 340, 200);

        jLabel52.setBackground(new java.awt.Color(255, 153, 204));
        jLabel52.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(208, 125, 43)));
        jLabel52.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel52.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel52.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel52);
        jLabel52.setBounds(420, 310, 110, 150);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/dislike.png"))); // NOI18N
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel53);
        jLabel53.setBounds(500, 470, 40, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/cart.png"))); // NOI18N
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel35);
        jLabel35.setBounds(420, 470, 40, 40);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/gallery/like.png"))); // NOI18N
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel54);
        jLabel54.setBounds(460, 470, 40, 40);

        jTextField45.setEditable(false);
        jTextField45.setBackground(new java.awt.Color(225, 225, 161));
        jTextField45.setForeground(new java.awt.Color(123, 80, 38));
        jTextField45.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField45);
        jTextField45.setBounds(460, 510, 30, 20);

        jTextField46.setEditable(false);
        jTextField46.setBackground(new java.awt.Color(225, 225, 161));
        jTextField46.setForeground(new java.awt.Color(123, 80, 38));
        jTextField46.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(123, 80, 38)));
        getContentPane().add(jTextField46);
        jTextField46.setBounds(500, 510, 30, 20);
        getContentPane().add(jLabel38);
        jLabel38.setBounds(730, 360, 40, 40);

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        form7 f7 = null;
        f7 = new form7();
        f7.setVisible(true);
   
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          s.Pflag=false;
        s.pause();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           s.Cflag=false;
        s.play();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formMouseMoved

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Blue Marquise");
        Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField25.setText(String.valueOf(art.getLike()));
  jTextField26.setText(String.valueOf(art.getDislike()));

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Anachorète endormi");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField27.setText(String.valueOf(art.getLike()));
  jTextField28.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("the death ofo edipus");
   Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField29.setText(String.valueOf(art.getLike()));
  jTextField30.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("the nightmare");
   Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField31.setText(String.valueOf(art.getLike()));
  jTextField32.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("The Seller of Cupids");
   Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField40.setText(String.valueOf(art.getLike()));
  jTextField39.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Union_of_Lublin");
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField33.setText(String.valueOf(art.getLike()));
  jTextField34.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Sweet Melancholy");
   Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField35.setText(String.valueOf(art.getLike()));
  jTextField36.setText(String.valueOf(art.getDislike()));
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Blue Marquise");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
          JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Blue Marquise", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }
          
         }
           
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Blue Marquise");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Blue Marquise", art);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Blue Marquise");
        int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put("Blue Marquise", art);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Anachorète endormi");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
         JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Anachorète endormi", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }}
        
            
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Anachorète endormi");
        int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Anachorète endormi", art);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("Anachorète endormi");
        int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put("Anachorète endormi", art);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
          art=artgallery.loading.ArtWork.get("the death ofo edipus");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
          JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("the death ofo edipus", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }}
        
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("the death ofo edipus");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("the death ofo edipus", art);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("the death ofo edipus");
         int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put("the death ofo edipus", art);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("the nightmare");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
          JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("the nightmare", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("the nightmare");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("the nightmare", art);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("the nightmare");
        int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put("the nightmare", art);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("The Seller of Cupids");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
         JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("The Seller of Cupids", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("The Seller of Cupids");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("The Seller of Cupids", art);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        art=artgallery.loading.ArtWork.get("The Seller of Cupids");
         int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put("The Seller of Cupids", art);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Union_of_Lublin");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
          JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Union_of_Lublin", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Union_of_Lublin");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Union_of_Lublin", art);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Union_of_Lublin");
         int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put("Union_of_Lublin", art);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
           art=artgallery.loading.ArtWork.get("Sweet Melancholy");
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
          JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put("Sweet Melancholy", art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Sweet Melancholy");
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put("Sweet Melancholy", art);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
         art=artgallery.loading.ArtWork.get("Sweet Melancholy");
         int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put("Sweet Melancholy", art);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        Hoverbar.setText(" ");
    }//GEN-LAST:event_jLabel1MouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
        artgallery.loading.add_Artwork(artgallery.loading);
    } catch (IOException ex) {
        Logger.getLogger(form10.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowClosing

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
art=artgallery.loading.ArtWork.get(artTitle);
  Hoverbar.setText("Artwork title: "+art.getTitle() +"\n"+ "Description: "+
                art.getDescription()+"\n"+"Price: "+art.getPrice()+"\n"+
                "Year: "+art.getYear()+"\n"+"Artist Name: "+art.getA().Name+"\n"+
                "Artist Birthplace: "+art.getA().Birthplace+"\n"
                +"Artist Age: "+art.getA().Age+"\n"+
                "Category: "+art.getA().Category);
  jTextField45.setText(String.valueOf(art.getLike()));
  jTextField46.setText(String.valueOf(art.getDislike()));        
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked

        art=artgallery.loading.ArtWork.get(artTitle);
         int dislike=art.getDislike();
         dislike+=1;
         art.setDislike(dislike);
        artgallery.loading.ArtWork.put(artTitle, art);
    }//GEN-LAST:event_jLabel53MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        
        art=artgallery.loading.ArtWork.get(artTitle);
        if (art.getCount()==0)
            JOptionPane.showMessageDialog(null,"Sold out ","ERROR",JOptionPane.ERROR_MESSAGE);
        else {
          JOptionPane.showMessageDialog(f,"Done ","Shoping process",JOptionPane.INFORMATION_MESSAGE);
          int count =art.getCount();
                  count-=1;
                  art.setCount(count);
          artgallery.loading.ArtWork.put(artTitle, art);
            try {
                f1.cust.Buy_anyitem(art.getPrice(), f1.cust);
            } catch (IOException ex) {
                Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked

        art=artgallery.loading.ArtWork.get(artTitle);
         int like=art.getLike();
         like+=1;
         art.setLike(like);
         artgallery.loading.ArtWork.put(artTitle, art);
    }//GEN-LAST:event_jLabel54MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form16().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(form16.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Hoverbar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    // End of variables declaration//GEN-END:variables
}
